In [2]:
#numpy: to perform mathematical or scientific operations.
#vector: a linear, one-dimensional array. It is used to store sequences of data, coordinates, or measurements efficiently
#matrix: a specialised, two-dimensional array.

In [3]:
import pandas as pd
import numpy as np 

In [4]:
nos=[[1,2,3,4],[5,6,7,8]]
nos

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
type(nos)

list

In [6]:
nos=np.array(nos)
nos

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
type(nos)

numpy.ndarray

In [8]:
np.array(range(0,10)) #use range conveniently without having to create a list and converting it into an array.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10) #use np.arange because its faster and doesn't need you to write 2 lines of code.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,5,6) #use linspace to create evenly spaced values.

array([0., 1., 2., 3., 4., 5.])

In [11]:
np.linspace(0,3,31) #starts from 0, stops at 3, gives you 31 values.

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [12]:
np.linspace(0,3,50)

array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ])

In [13]:
eg=[[1,2,3],[10,20,30]]

In [14]:
np.array(eg)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [15]:
np.ones((10,5)) #creates rows,columns. there are double brackets because the size of the array is mentioned in a tuple.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#ones creates a new array of a specified shape and data type, filled entirely with the value.

In [17]:
np.zeros((3,4)) #gives you a matrix (rows, columns) of size 3*4 filled with zeros. here we have used a tuple because it's a multidimensional argument.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
first_thirty=np.linspace(0,29,30)
print(first_thirty)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


In [21]:
first_thirty.shape #shape is a method. we know this because upon putting (), it will show an error. only functions use ().

(30,)

In [25]:
first_thirty.reshape(3,10) #reshape is a function. we have now created a matrix of 3*10 of the first thirty numbers. 

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [26]:
#selecting from numpy array (indexing)

In [27]:
first_ten=np.arange(0,10)
print(first_ten)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
first_ten[3]

3

In [30]:
first_ten[3:5] #starting from index 3 (including) to index 5 (excluding)

array([3, 4])

In [31]:
first_ten[:2] #starting from the beginning to index 2 (excluding)

array([0, 1])

In [32]:
first_ten[6:] #starting from index 6 (including) to the end

array([6, 7, 8, 9])

In [33]:
first_thirty=np.linspace(0,29,30)
three_by_ten=first_thirty.reshape(3,10)
print(three_by_ten)
print(three_by_ten.shape)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]]
(3, 10)


In [34]:
three_by_ten[1] #here only the first row will be printed

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [35]:
three_by_ten[1,5] #to print only 15 from the dataset by inserting the index number of the matrix

15.0

In [36]:
three_by_ten[0:2,1:3]

array([[ 1.,  2.],
       [11., 12.]])

In [41]:
tens=np.arange(0,101)
print(tens)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
